version: '3.4'

services:
  statusserver:
    image: statusserver
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start.dev
    environment:
      NODE_ENV: development
      START: dev
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_USER: ${API_SERVER_MQTT_USER}
      MQTT_PASSWORD: ${API_SERVER_MQTT_PASSWD}
      CONTAINER_PORT: ${API_SERVER_PORT}
      DATADIR: ${API_SERVER_DATADIR}
      TZ: ${API_SERVER_TZ}
    ports:
      - 3000:${API_SERVER_PORT}
    volumes: 
      - .:/usr/src/app
      - /dev/null:/usr/src/app/.env
      - /usr/src/app/node_modules
      - ./testing/data:/data
