version: '3.4'

services:
  statusserver:
    image: statusserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./testing/data:/data
