
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: random
    name: temp1
    minimum: 23
    maximum: 29
    unit_of_measurement: "°C"

homeassistant:
  customize:
    sensor.temp1:
      friendly_name: Temperature Living Room
      icon: mdi:thermometer
    group.living_room:
      friendly_name: Living Room
    
